### ISSUE TITLE
Link color missing

### ISSUE THREAD

**Issue by Astisme** [github/mona-sans#43]
If this font is included in a link, it doesn't get colored; furthermore, there's no way to assign a color to the font via the `color` attribute.

Put it simply, this command does nothing when using mona or hubot sans:
```css
a {
  color: #f2f2f2;
}
```
