### ISSUE TITLE
Incorrect Default Style in MonaSans[ital,wdth,wght].woff2 – Displayed as Italic Despite font-style: normal

### ISSUE THREAD

**Issue by edding-3000** [github/mona-sans#88]
## Description:
When using the variable font “MonaSans[ital,wdth,wght].woff2” on a website and embedding it via CSS, the text is incorrectly displayed in italic, even though ```font-style: normal``` is explicitly set and no ```font-variation-settings``` are applied. The PostScript name is also reported as “MonaSans-ExtraLightItalic”.

<img width="298" alt="Image" src="https://github.com/user-attachments/assets/316a47b5-4b13-4488-bbb6-ae7099c05de0" />

<br />

## Steps to Reproduce:

1. Embed MonaSans[ital,wdth,wght].woff2 via CSS:

```CSS
@font-face {
font-family: 'Mona Sans Variable';
src: url('/fonts/MonaSans[ital,wdth,wght].woff2') format('woff2');
font-style: normal;
font-weight: 200 900;
}
```

2. Apply the font to an element with font-style: normal;
3. Observe that the text is still rendered in italic.

## Environment:

Browser: Chrome Version 137.0.7151.56, Safari Version 18.5
OS: macOS Sequoia 15.5
Font file version: 2.000
